

export const themes = [
    {
        id: 'cozy-pink',
        name: 'Cozy Pink',
        colors: {
            '--color-background': '#201f24',
            '--color-surface': '#2a282f',
            '--color-surface-light': '#3b3842',
            '--color-primary': '#f5e6e8',
            '--color-secondary': '#a099a6',
            '--color-border': '#3b3842',
            '--color-accent': '#ffc0cb',
            '--color-accent-rgb': '255, 192, 203',
            '--color-accent-2': '#c5e8d8',
            '--color-accent-3': '#ffddc1',
            '--color-accent-4': '#c8e0f4',
            '--color-accent-5': '#daccff',
        },
    },
    {
        id: 'forest',
        name: 'Forest',
        colors: {
            '--color-background': '#222725',
            '--color-surface': '#2C332F',
            '--color-surface-light': '#3A423D',
            '--color-primary': '#E8EAE8',
            '--color-secondary': '#A2A8A4',
            '--color-border': '#3A423D',
            '--color-accent': '#A3BDA2',
            '--color-accent-rgb': '163, 189, 162',
            '--color-accent-2': '#E8D9C0',
            '--color-accent-3': '#D4BFA4',
            '--color-accent-4': '#8E9E87',
            '--color-accent-5': '#C8D1C3',
        },
    },
    {
        id: 'ocean',
        name: 'Ocean',
        colors: {
            '--color-background': '#1F232D',
            '--color-surface': '#272D3A',
            '--color-surface-light': '#333A4A',
            '--color-primary': '#E4E7F0',
            '--color-secondary': '#9DA3B0',
            '--color-border': '#333A4A',
            '--color-accent': '#89B4FA',
            '--color-accent-rgb': '137, 180, 250',
            '--color-accent-2': '#B4E8E2',
            '--color-accent-3': '#F5C2E7',
            '--color-accent-4': '#ABE9B3',
            '--color-accent-5': '#F9E2AF',
        },
    },
    {
        id: 'sunset',
        name: 'Sunset',
        colors: {
            '--color-background': '#292121',
            '--color-surface': '#362A2A',
            '--color-surface-light': '#453838',
            '--color-primary': '#F5EBE0',
            '--color-secondary': '#B8A8A1',
            '--color-border': '#453838',
            '--color-accent': '#FAB387',
            '--color-accent-rgb': '250, 179, 135',
            '--color-accent-2': '#F2CDCD',
            '--color-accent-3': '#DDB6F2',
            '--color-accent-4': '#ABE9B3',
            '--color-accent-5': '#96CDFB',
        },
    },
    {
        id: 'lavender',
        name: 'Lavender',
        colors: {
            '--color-background': '#24222C',
            '--color-surface': '#2E2B38',
            '--color-surface-light': '#3C384A',
            '--color-primary': '#E9E7F3',
            '--color-secondary': '#A8A3B8',
            '--color-border': '#3C384A',
            '--color-accent': '#CBA6F7',
            '--color-accent-rgb': '203, 166, 247',
            '--color-accent-2': '#89B4FA',
            '--color-accent-3': '#F5C2E7',
            '--color-accent-4': '#94E2D5',
            '--color-accent-5': '#FAB387',
        },
    },
];

export const DEFAULT_THEME_ID = 'ocean';
export const DEFAULT_BANNER_URL = 'https://soranews24.com/wp-content/uploads/sites/3/2015/07/tumblr_njlqclfisw1qze3hdo1_r2_500.gif';
